import { useEffect, useState } from "react";
import { ExternalLink, FileText } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface RegionFichaProps {
  regionId: string;
}

/** Resolve the per-region ficha HTML under the deployed base path. */
function fichaUrl(regionId: string): string {
  return `${import.meta.env.BASE_URL}fichas/${regionId}.html`;
}

/**
 * Link to the standalone multi-source ficha (Plotly HTML, one per RGINT),
 * generated by data_pipeline/03_generate_reports.py into webapp/public/fichas/.
 * Probes for presence so regions without a ficha hide the card.
 */
export function RegionFicha({ regionId }: RegionFichaProps) {
  const url = fichaUrl(regionId);
  const [available, setAvailable] = useState<boolean | null>(null);

  useEffect(() => {
    let active = true;
    setAvailable(null);
    fetch(url, { method: "HEAD" })
      .then((r) => active && setAvailable(r.ok))
      .catch(() => active && setAvailable(false));
    return () => {
      active = false;
    };
  }, [url]);

  if (available === false) return null;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Ficha completa</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          aria-disabled={available !== true}
          className="flex w-full items-center justify-between gap-2 rounded border border-border px-3 py-2 text-left text-sm text-foreground transition-colors hover:bg-highlight aria-disabled:pointer-events-none aria-disabled:opacity-40"
        >
          <span className="inline-flex items-center gap-2">
            <FileText className="h-4 w-4 shrink-0 text-muted" />
            Abrir ficha multi-fonte
          </span>
          <ExternalLink className="h-3.5 w-3.5 shrink-0 text-muted" />
        </a>
        <p className="text-xs text-muted">
          Séries de todas as fontes (MapBiomas, LAPIG, TerraClass, PAM, CONAB)
          por classe, em gráficos lineares. Abre em nova aba.
        </p>
      </CardContent>
    </Card>
  );
}
